### PR TITLE
Dark theme go select 676

### LINKED ISSUE #676: [BUG] Dark Theme on go-select
**Describe the bug**
The `go-select` does not have appropriate styling applied when `theme="dark"` is set. The label and hints are styled correctly, but the actual `ng-select` component is not styled correctly.

**To Reproduce**
1. Create a `go-select` with `theme="dark"` set
2. See that the `ng-select` element is not styled correctly

Stackblitz Example:
https://stackblitz.com/edit/goponents-dark-go-select

**Expected behavior**
I would expect the `ng-select` element and dropdown to be styled in a way that matches the overall dark theme.

### PR DESCRIPTION
**Pull request by Ashygoyal**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [guidelines](https://github.com/mobi/goponents/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added
- [ ] Docs have been added or updated

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Style Update (CSS)
- [ ] Other... Please describe:

## What is the current behavior?
The current styling for dark versions of go-input and go-select, are not as per DSM guidelines.

Resolves #676 

## What is the new behavior?
The go-input and go-select now have updated styles for their dark versions, as per latest DSM guidelines.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by grahamhency — CHANGES_REQUESTED** [review]
@Ashygoyal I think the original issue was intended to add styles to the `ng-select` component inside of the `go-select` component. We have a binding already for `theme` there, but we're not properly adjusting the styles of the actual input or dropdown generated by `ng-select`.

I think the code you've already changed here is good, but we'll want to update the `go-select` as well.

**Comment by Ashygoyal** [comment]
> @Ashygoyal I think the original issue was intended to add styles to the `ng-select` component inside of the `go-select` component. We have a binding already for `theme` there, but we're not properly adjusting the styles of the actual input or dropdown generated by `ng-select`.
> 
> I think the code you've already changed here is good, but we'll want to update the `go-select` as well.

Hey @grahamhency , I just pushed the ng-select styles for dark theme as close as possible to the DSM guidelines!
This is the end result:
Screenshot (280)
I think the newly added css code can still be improved, need your inputs!

**Review by grahamhency — CHANGES_REQUESTED** [review]
Hey @Ashygoyal, your first pass at this was good. I pulled down the branch just to see what it looked like and there were a couple things that needed addressed (borders mainly), but I went ahead and just made those changes as well as cleaned up the SCSS a bit while I had the branch there.

I think we're good with these changes, but feel free to look them over (just make sure to pull down my changes first!) and then me know what you think.

The only other thing we will need for this is to document the dark theme capability. Would you mind adding that?

**Comment by Ashygoyal** [comment]
> I think we're good with these changes, but feel free to look them over (just make sure to pull down my changes first!) and then me know what you think.
> 
> The only other thing we will need for this is to document the dark theme capability. Would you mind adding that?

Hey @grahamhency , thanks a ton for fixing the SCSS changes.
I just updated the go-select docs.

**Review by grahamhency — APPROVED** [review]
Looks good to me, I say merge it!

**Pull request merged**
